name: Push Build

on:
  workflow_dispatch:
  repository_dispatch:
    types: [push-build]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: outsidee-Inc/gds-data
          token: ${{ secrets.GDS_DATA }}
          path: src
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust build cache
        uses: Swatinem/rust-cache@v2
     
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install dependencies
        run: |
          if ! command -v cargo-set-version >/dev/null 2>&1; then
            echo "Installing cargo-edit..."
            cargo install cargo-edit --locked
          fi
        working-directory: src
        env:
          RUSTC_WRAPPER: sccache

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        working-directory: src

      - name: Version update
        run: | 
          make bump-patch-with-sha
          make install
        working-directory: src
        env:
          RUSTC_WRAPPER: sccache

      - name: Git Operations
        run: |
          if git diff --quiet && git diff --cached --quiet; then
              echo "No changes to commit"
              exit 0
          fi

          git add .
          git commit -m "chore: update bin version [skip ci]"
          
          git remote set-url origin https://x-access-token:${{ secrets.GDS_DATA }}@github.com/outsidee-Inc/gds-data.git
          git push origin HEAD:main
        working-directory: src