name: Push Excel Process

on:
  repository_dispatch:
    types: [push-excel-process]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: outsidee-Inc/gds-data
          token: ${{ secrets.GDS_DATA }}
          path: src